### PR TITLE
Added CUDA 10.1 compatibility

### PR DESCRIPTION
**Pull request by ZuluPro**
Due to compilation option, install wasn't available from package.

### CODE REVIEW

**Comment by f0k** [comment]
Thank you for the PR! Could you please comment a bit on what wasn't working?
1. Which OS did you try to compile on?
2. Does it fail with `-O`, but work with `-O3`?
3. Is there any `nvcc` version that would not support `-O3`, or can we just omit the version check?
Thank you!

**Comment by ZuluPro** [comment]
Hello @f0k 
Sorry for the delay,
Let me find a GPU VM and I'll say you.

**Comment by ynsgnr** [comment]
@f0k I checked the documentation and for older versions default value is 3 for optimization anyway:
https://docs.nvidia.com/cuda/archive/9.2/cuda-compiler-driver-nvcc/index.html#ptxas-options

So technically there is no need for version check but I didnt try to compile with every version

**Comment by f0k** [comment]
@ynsgnr Thanks for the pointer! I checked with an old CUDA version (4.0), it doesn't do `-O3` by default, but according to the documentation, it also expects the level to be given. So `nvcc -O` (without a level) should never have worked. I had taken it from [the original cudamat Makefile](https://github.com/cudamat/cudamat/blob/3803b3b4905403b9f00de742b98917389890cb00/Makefile).

So the correct solution would be to unconditionally pass `-O3` instead of `-O`. @ZuluPro, can you amend your commit (i.e., change your code, do `git commit -a --amend`, then `git push --force`)? If it's too much of a hassle, I can do it myself. Cheers!

**Comment by f0k** [comment]
Merged manually since I couldn't push the requested change to your fork.

**Pull request closed without merging**
